services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  url-shorter:
    image: korgi-link:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"

volumes:
  db_data: